In [68]:
import json
from pprint import pprint

with open('data.json') as f:
    data = json.load(f)
    pprint(data)
data.keys()

{'DesignWorks': [{'contract_hours': 40,
                  'hourly_rate': 40,
                  'job': 'Analyste',
                  'name': 'Jack',
                  'weekly_hours_worked': 38},
                 {'contract_hours': 40,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Emma',
                  'weekly_hours_worked': 34},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Ian',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Tina',
                  'weekly_hours_worked': 48},
                 {'contract_hours': 40,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Oliver',
                  'weekly_hours_worked': 49},
                 {'contract_hours': 35,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Jack',
                  'weekly_hours_worked': 33},
                 {'contract_hours': 40,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Oliver',
                  'weekly_hours_worked': 45},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Rachel',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 37,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Ian',
                  'weekly_hours_worked': 43},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Jack',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 35,
                  'hourly_rate': 40,
                  'job': 'Analyste',
                  'name': 'Rachel',
                  'weekly_hours_worked': 32},
                 {'contract_hours': 35,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Helen',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 40,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'George',
                  'weekly_hours_worked': 30},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Rachel',
                  'weekly_hours_worked': 48},
                 {'contract_hours': 37,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Emma',
                  'weekly_hours_worked': 44},
                 {'contract_hours': 40,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Mike',
                  'weekly_hours_worked': 32},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Ian',
                  'weekly_hours_worked': 39},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Bob',
                  'weekly_hours_worked': 45}],
 'ProjectLead': [{'contract_hours': 40,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Fred',
                  'weekly_hours_worked': 49},
                 {'contract_hours': 37,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Mike',
                  'weekly_hours_worked': 32},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Oliver',
                  'weekly_hours_worked': 38},
                 {'contract_hours': 37,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Tina',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 37,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Linda',
                  'weekly_hours_worked': 39},
                 {'contract_hours': 35,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Rachel',
                  'weekly_hours_worked': 48},
                 {'contract_hours': 35,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Bob',
                  'weekly_hours_worked': 46},
                 {'contract_hours': 37,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Steve',
                  'weekly_hours_worked': 44},
                 {'contract_hours': 37,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Jack',
                  'weekly_hours_worked': 31},
                 {'contract_hours': 35,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Jack',
                  'weekly_hours_worked': 46},
                 {'contract_hours': 37,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Charlie',
                  'weekly_hours_worked': 43},
                 {'contract_hours': 37,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Oliver',
                  'weekly_hours_worked': 35},
                 {'contract_hours': 40,
                  'hourly_rate': 40,
                  'job': 'Analyste',
                  'name': 'Nina',
                  'weekly_hours_worked': 45},
                 {'contract_hours': 37,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Steve',
                  'weekly_hours_worked': 42},
                 {'contract_hours': 35,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Linda',
                  'weekly_hours_worked': 36},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Jack',
                  'weekly_hours_worked': 46},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Charlie',
                  'weekly_hours_worked': 40}],
 'TechCorp': [{'contract_hours': 37,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Helen',
               'weekly_hours_worked': 44},
              {'contract_hours': 40,
               'hourly_rate': 28,
               'job': 'Testeur',
               'name': 'Quincy',
               'weekly_hours_worked': 48},
              {'contract_hours': 40,
               'hourly_rate': 55,
               'job': 'Manager',
               'name': 'Fred',
               'weekly_hours_worked': 33},
              {'contract_hours': 40,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Steve',
               'weekly_hours_worked': 32},
              {'contract_hours': 35,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Linda',
               'weekly_hours_worked': 34},
              {'contract_hours': 40,
               'hourly_rate': 40,
               'job': 'Analyste',
               'name': 'Bob',
               'weekly_hours_worked': 35},
              {'contract_hours': 37,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Steve',
               'weekly_hours_worked': 50},
              {'contract_hours': 40,
               'hourly_rate': 35,
               'job': 'Développeur',
               'name': 'Karen',
               'weekly_hours_worked': 33},
              {'contract_hours': 35,
               'hourly_rate': 30,
               'job': 'Designer',
               'name': 'Paul',
               'weekly_hours_worked': 30},
              {'contract_hours': 35,
               'hourly_rate': 35,
               'job': 'Développeur',
               'name': 'Bob',
               'weekly_hours_worked': 48},
              {'contract_hours': 35,
               'hourly_rate': 55,
               'job': 'Manager',
               'name': 'Bob',
               'weekly_hours_worked': 45},
              {'contract_hours': 40,
               'hourly_rate': 28,
               'job': 'Testeur',
               'name': 'Mike',
               'weekly_hours_worked': 33},
              {'contract_hours': 40,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Mike',
               'weekly_hours_worked': 43},
              {'contract_hours': 37,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Charlie',
               'weekly_hours_worked': 32},
              {'contract_hours': 35,
               'hourly_rate': 28,
               'job': 'Testeur',
               'name': 'Helen',
               'weekly_hours_worked': 48}]}

dict_keys(['TechCorp', 'DesignWorks', 'ProjectLead'])

In [38]:
len(data)

3

In [39]:
for key, value in data.items():
    for i in value:
        if i['weekly_hours_worked'] > i['contract_hours']:
            i['week_salary'] = i['contract_hours'] * i['hourly_rate'] + \
                (i['weekly_hours_worked'] - i['contract_hours']) * i['hourly_rate'] * 1.5
            i['monthly_salary'] = i['week_salary'] * 4
        else:
            i['week_salary'] = i['weekly_hours_worked'] * i['hourly_rate']
            i['monthly_salary'] = i['week_salary'] * 4

In [40]:
len(data)

3

In [41]:
40*35

1400

In [67]:
import json
from pprint import pprint

with open('data.json') as f:
    data = json.load(f)
    pprint(data)
data['TechCorp']

{'DesignWorks': [{'contract_hours': 40,
                  'hourly_rate': 40,
                  'job': 'Analyste',
                  'name': 'Jack',
                  'weekly_hours_worked': 38},
                 {'contract_hours': 40,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Emma',
                  'weekly_hours_worked': 34},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Ian',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Tina',
                  'weekly_hours_worked': 48},
                 {'contract_hours': 40,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Oliver',
                  'weekly_hours_worked': 49},
                 {'contract_hours': 35,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Jack',
                  'weekly_hours_worked': 33},
                 {'contract_hours': 40,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Oliver',
                  'weekly_hours_worked': 45},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Rachel',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 37,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Ian',
                  'weekly_hours_worked': 43},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Jack',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 35,
                  'hourly_rate': 40,
                  'job': 'Analyste',
                  'name': 'Rachel',
                  'weekly_hours_worked': 32},
                 {'contract_hours': 35,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Helen',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 40,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'George',
                  'weekly_hours_worked': 30},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Rachel',
                  'weekly_hours_worked': 48},
                 {'contract_hours': 37,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Emma',
                  'weekly_hours_worked': 44},
                 {'contract_hours': 40,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Mike',
                  'weekly_hours_worked': 32},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Ian',
                  'weekly_hours_worked': 39},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Bob',
                  'weekly_hours_worked': 45}],
 'ProjectLead': [{'contract_hours': 40,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Fred',
                  'weekly_hours_worked': 49},
                 {'contract_hours': 37,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Mike',
                  'weekly_hours_worked': 32},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Oliver',
                  'weekly_hours_worked': 38},
                 {'contract_hours': 37,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Tina',
                  'weekly_hours_worked': 37},
                 {'contract_hours': 37,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Linda',
                  'weekly_hours_worked': 39},
                 {'contract_hours': 35,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Rachel',
                  'weekly_hours_worked': 48},
                 {'contract_hours': 35,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Bob',
                  'weekly_hours_worked': 46},
                 {'contract_hours': 37,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Steve',
                  'weekly_hours_worked': 44},
                 {'contract_hours': 37,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Jack',
                  'weekly_hours_worked': 31},
                 {'contract_hours': 35,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Jack',
                  'weekly_hours_worked': 46},
                 {'contract_hours': 37,
                  'hourly_rate': 55,
                  'job': 'Manager',
                  'name': 'Charlie',
                  'weekly_hours_worked': 43},
                 {'contract_hours': 37,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Oliver',
                  'weekly_hours_worked': 35},
                 {'contract_hours': 40,
                  'hourly_rate': 40,
                  'job': 'Analyste',
                  'name': 'Nina',
                  'weekly_hours_worked': 45},
                 {'contract_hours': 37,
                  'hourly_rate': 30,
                  'job': 'Designer',
                  'name': 'Steve',
                  'weekly_hours_worked': 42},
                 {'contract_hours': 35,
                  'hourly_rate': 35,
                  'job': 'Développeur',
                  'name': 'Linda',
                  'weekly_hours_worked': 36},
                 {'contract_hours': 35,
                  'hourly_rate': 28,
                  'job': 'Testeur',
                  'name': 'Jack',
                  'weekly_hours_worked': 46},
                 {'contract_hours': 35,
                  'hourly_rate': 50,
                  'job': 'Chef de projet',
                  'name': 'Charlie',
                  'weekly_hours_worked': 40}],
 'TechCorp': [{'contract_hours': 37,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Helen',
               'weekly_hours_worked': 44},
              {'contract_hours': 40,
               'hourly_rate': 28,
               'job': 'Testeur',
               'name': 'Quincy',
               'weekly_hours_worked': 48},
              {'contract_hours': 40,
               'hourly_rate': 55,
               'job': 'Manager',
               'name': 'Fred',
               'weekly_hours_worked': 33},
              {'contract_hours': 40,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Steve',
               'weekly_hours_worked': 32},
              {'contract_hours': 35,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Linda',
               'weekly_hours_worked': 34},
              {'contract_hours': 40,
               'hourly_rate': 40,
               'job': 'Analyste',
               'name': 'Bob',
               'weekly_hours_worked': 35},
              {'contract_hours': 37,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Steve',
               'weekly_hours_worked': 50},
              {'contract_hours': 40,
               'hourly_rate': 35,
               'job': 'Développeur',
               'name': 'Karen',
               'weekly_hours_worked': 33},
              {'contract_hours': 35,
               'hourly_rate': 30,
               'job': 'Designer',
               'name': 'Paul',
               'weekly_hours_worked': 30},
              {'contract_hours': 35,
               'hourly_rate': 35,
               'job': 'Développeur',
               'name': 'Bob',
               'weekly_hours_worked': 48},
              {'contract_hours': 35,
               'hourly_rate': 55,
               'job': 'Manager',
               'name': 'Bob',
               'weekly_hours_worked': 45},
              {'contract_hours': 40,
               'hourly_rate': 28,
               'job': 'Testeur',
               'name': 'Mike',
               'weekly_hours_worked': 33},
              {'contract_hours': 40,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Mike',
               'weekly_hours_worked': 43},
              {'contract_hours': 37,
               'hourly_rate': 50,
               'job': 'Chef de projet',
               'name': 'Charlie',
               'weekly_hours_worked': 32},
              {'contract_hours': 35,
               'hourly_rate': 28,
               'job': 'Testeur',
               'name': 'Helen',
               'weekly_hours_worked': 48}]}

[{'name': 'Helen',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 44,
  'contract_hours': 37},
 {'name': 'Quincy',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 40},
 {'name': 'Fred',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 32,
  'contract_hours': 40},
 {'name': 'Linda',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 34,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Analyste',
  'hourly_rate': 40,
  'weekly_hours_worked': 35,
  'contract_hours': 40},
 {'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 50,
  'contract_hours': 37},
 {'name': 'Karen',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Paul',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 30,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 45,
  'contract_hours': 35},
 {'name': 'Mike',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Mike',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 43,
  'contract_hours': 40},
 {'name': 'Charlie',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 32,
  'contract_hours': 37},
 {'name': 'Helen',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 35}]

In [51]:
data_length = len(data['TechCorp']) + len(data['DesignWorks']) + len(data['ProjectLead'])
mean_sal = 0
for key, value in data.items():
    for i in value:
        mean_sal += i['monthly_salary']

mean_sal = mean_sal /data_length

In [52]:
mean_sal

6883.6

In [70]:
all_data = []
import json
from pprint import pprint

with open('data.json') as f:
    data = json.load(f)
    
for x in data:
    for y in data[x]:
        all_data.append(y)

all_data

[{'name': 'Helen',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 44,
  'contract_hours': 37},
 {'name': 'Quincy',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 40},
 {'name': 'Fred',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 32,
  'contract_hours': 40},
 {'name': 'Linda',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 34,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Analyste',
  'hourly_rate': 40,
  'weekly_hours_worked': 35,
  'contract_hours': 40},
 {'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 50,
  'contract_hours': 37},
 {'name': 'Karen',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Paul',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 30,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 45,
  'contract_hours': 35},
 {'name': 'Mike',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Mike',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 43,
  'contract_hours': 40},
 {'name': 'Charlie',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 32,
  'contract_hours': 37},
 {'name': 'Helen',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Jack',
  'job': 'Analyste',
  'hourly_rate': 40,
  'weekly_hours_worked': 38,
  'contract_hours': 40},
 {'name': 'Emma',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 34,
  'contract_hours': 40},
 {'name': 'Ian',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 37,
  'contract_hours': 35},
 {'name': 'Tina',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Oliver',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 49,
  'contract_hours': 40},
 {'name': 'Jack',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 33,
  'contract_hours': 35},
 {'name': 'Oliver',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 45,
  'contract_hours': 40},
 {'name': 'Rachel',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 37,
  'contract_hours': 35},
 {'name': 'Ian',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 43,
  'contract_hours': 37},
 {'name': 'Jack',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 37,
  'contract_hours': 35},
 {'name': 'Rachel',
  'job': 'Analyste',
  'hourly_rate': 40,
  'weekly_hours_worked': 32,
  'contract_hours': 35},
 {'name': 'Helen',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 37,
  'contract_hours': 35},
 {'name': 'George',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 30,
  'contract_hours': 40},
 {'name': 'Rachel',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Emma',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 44,
  'contract_hours': 37},
 {'name': 'Mike',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 32,
  'contract_hours': 40},
 {'name': 'Ian',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 39,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 45,
  'contract_hours': 35},
 {'name': 'Fred',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 49,
  'contract_hours': 40},
 {'name': 'Mike',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 32,
  'contract_hours': 37},
 {'name': 'Oliver',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 38,
  'contract_hours': 35},
 {'name': 'Tina',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 37,
  'contract_hours': 37},
 {'name': 'Linda',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 39,
  'contract_hours': 37},
 {'name': 'Rachel',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 46,
  'contract_hours': 35},
 {'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 44,
  'contract_hours': 37},
 {'name': 'Jack',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 31,
  'contract_hours': 37},
 {'name': 'Jack',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 46,
  'contract_hours': 35},
 {'name': 'Charlie',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 43,
  'contract_hours': 37},
 {'name': 'Oliver',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 35,
  'contract_hours': 37},
 {'name': 'Nina',
  'job': 'Analyste',
  'hourly_rate': 40,
  'weekly_hours_worked': 45,
  'contract_hours': 40},
 {'name': 'Steve',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 42,
  'contract_hours': 37},
 {'name': 'Linda',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 36,
  'contract_hours': 35},
 {'name': 'Jack',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 46,
  'contract_hours': 35},
 {'name': 'Charlie',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 40,
  'contract_hours': 35}]

In [55]:
data.keys()

dict_keys(['TechCorp', 'DesignWorks', 'ProjectLead'])

In [ ]:
#TODO:

{'name': 'Helen', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 44, 'contract_hours': 37, 'week_salary': 2375.0, 'monthly_salary': 9500.0}
{'name': 'Quincy', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 40, 'week_salary': 1456.0, 'monthly_salary': 5824.0}
{'name': 'Fred', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 33, 'contract_hours': 40, 'week_salary': 1815, 'monthly_salary': 7260}
{'name': 'Steve', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 32, 'contract_hours': 40, 'week_salary': 1600, 'monthly_salary': 6400}
{'name': 'Linda', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 34, 'contract_hours': 35, 'week_salary': 1700, 'monthly_salary': 6800}
{'name': 'Bob', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 35, 'contract_hours': 40, 'week_salary': 1400, 'monthly_salary': 5600}
{'name': 'Steve', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 50, 'contract_hours': 37, 'week_salary': 2825.0, 'monthly_salary': 11300.0}
{'name': 'Karen', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 33, 'contract_hours': 40, 'week_salary': 1155, 'monthly_salary': 4620}
{'name': 'Paul', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 30, 'contract_hours': 35, 'week_salary': 900, 'monthly_salary': 3600}
{'name': 'Bob', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 48, 'contract_hours': 35, 'week_salary': 1907.5, 'monthly_salary': 7630.0}
{'name': 'Bob', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 45, 'contract_hours': 35, 'week_salary': 2750.0, 'monthly_salary': 11000.0}
{'name': 'Mike', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 33, 'contract_hours': 40, 'week_salary': 924, 'monthly_salary': 3696}
{'name': 'Mike', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 43, 'contract_hours': 40, 'week_salary': 2225.0, 'monthly_salary': 8900.0}
{'name': 'Charlie', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 32, 'contract_hours': 37, 'week_salary': 1600, 'monthly_salary': 6400}
{'name': 'Helen', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 35, 'week_salary': 1526.0, 'monthly_salary': 6104.0}
{'name': 'Jack', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 38, 'contract_hours': 40, 'week_salary': 1520, 'monthly_salary': 6080}
{'name': 'Emma', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 34, 'contract_hours': 40, 'week_salary': 1020, 'monthly_salary': 4080}
{'name': 'Ian', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 37, 'contract_hours': 35, 'week_salary': 1900.0, 'monthly_salary': 7600.0}
{'name': 'Tina', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 35, 'week_salary': 1526.0, 'monthly_salary': 6104.0}
{'name': 'Oliver', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 49, 'contract_hours': 40, 'week_salary': 2675.0, 'monthly_salary': 10700.0}
{'name': 'Jack', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 33, 'contract_hours': 35, 'week_salary': 990, 'monthly_salary': 3960}
{'name': 'Oliver', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 45, 'contract_hours': 40, 'week_salary': 2612.5, 'monthly_salary': 10450.0}
{'name': 'Rachel', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 37, 'contract_hours': 35, 'week_salary': 1064.0, 'monthly_salary': 4256.0}
{'name': 'Ian', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 43, 'contract_hours': 37, 'week_salary': 1288.0, 'monthly_salary': 5152.0}
{'name': 'Jack', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 37, 'contract_hours': 35, 'week_salary': 1900.0, 'monthly_salary': 7600.0}
{'name': 'Rachel', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 32, 'contract_hours': 35, 'week_salary': 1280, 'monthly_salary': 5120}
{'name': 'Helen', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 37, 'contract_hours': 35, 'week_salary': 1330.0, 'monthly_salary': 5320.0}
{'name': 'George', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 30, 'contract_hours': 40, 'week_salary': 1050, 'monthly_salary': 4200}
{'name': 'Rachel', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 35, 'week_salary': 1526.0, 'monthly_salary': 6104.0}
{'name': 'Emma', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 44, 'contract_hours': 37, 'week_salary': 2375.0, 'monthly_salary': 9500.0}
{'name': 'Mike', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 32, 'contract_hours': 40, 'week_salary': 1760, 'monthly_salary': 7040}
{'name': 'Ian', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 39, 'contract_hours': 35, 'week_salary': 2050.0, 'monthly_salary': 8200.0}
{'name': 'Bob', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 45, 'contract_hours': 35, 'week_salary': 2500.0, 'monthly_salary': 10000.0}
{'name': 'Fred', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 49, 'contract_hours': 40, 'week_salary': 1498.0, 'monthly_salary': 5992.0}
{'name': 'Mike', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 32, 'contract_hours': 37, 'week_salary': 1120, 'monthly_salary': 4480}
{'name': 'Oliver', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 38, 'contract_hours': 35, 'week_salary': 1975.0, 'monthly_salary': 7900.0}
{'name': 'Tina', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 37, 'contract_hours': 37, 'week_salary': 2035, 'monthly_salary': 8140}
{'name': 'Linda', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 39, 'contract_hours': 37, 'week_salary': 1120.0, 'monthly_salary': 4480.0}
{'name': 'Rachel', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 48, 'contract_hours': 35, 'week_salary': 1635.0, 'monthly_salary': 6540.0}
{'name': 'Bob', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 46, 'contract_hours': 35, 'week_salary': 2832.5, 'monthly_salary': 11330.0}
{'name': 'Steve', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 44, 'contract_hours': 37, 'week_salary': 2375.0, 'monthly_salary': 9500.0}
{'name': 'Jack', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 31, 'contract_hours': 37, 'week_salary': 1550, 'monthly_salary': 6200}
{'name': 'Jack', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 46, 'contract_hours': 35, 'week_salary': 1545.0, 'monthly_salary': 6180.0}
{'name': 'Charlie', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 43, 'contract_hours': 37, 'week_salary': 2530.0, 'monthly_salary': 10120.0}
{'name': 'Oliver', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 35, 'contract_hours': 37, 'week_salary': 1225, 'monthly_salary': 4900}
{'name': 'Nina', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 45, 'contract_hours': 40, 'week_salary': 1900.0, 'monthly_salary': 7600.0}
{'name': 'Steve', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 42, 'contract_hours': 37, 'week_salary': 1335.0, 'monthly_salary': 5340.0}
{'name': 'Linda', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 36, 'contract_hours': 35, 'week_salary': 1277.5, 'monthly_salary': 5110.0}
{'name': 'Jack', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 46, 'contract_hours': 35, 'week_salary': 1442.0, 'monthly_salary': 5768.0}
{'name': 'Charlie', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 40, 'contract_hours': 35, 'week_salary': 2125.0, 'monthly_salary': 8500.0}

In [73]:
for i in data:
    print(i)
    data[i].sort(key=lambda x: x['weekly_hours_worked'], reverse=True)

TechCorp
DesignWorks
ProjectLead

In [74]:
data['TechCorp']

[{'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 50,
  'contract_hours': 37},
 {'name': 'Quincy',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 40},
 {'name': 'Bob',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Helen',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 48,
  'contract_hours': 35},
 {'name': 'Bob',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 45,
  'contract_hours': 35},
 {'name': 'Helen',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 44,
  'contract_hours': 37},
 {'name': 'Mike',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 43,
  'contract_hours': 40},
 {'name': 'Bob',
  'job': 'Analyste',
  'hourly_rate': 40,
  'weekly_hours_worked': 35,
  'contract_hours': 40},
 {'name': 'Linda',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 34,
  'contract_hours': 35},
 {'name': 'Fred',
  'job': 'Manager',
  'hourly_rate': 55,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Karen',
  'job': 'Développeur',
  'hourly_rate': 35,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Mike',
  'job': 'Testeur',
  'hourly_rate': 28,
  'weekly_hours_worked': 33,
  'contract_hours': 40},
 {'name': 'Steve',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 32,
  'contract_hours': 40},
 {'name': 'Charlie',
  'job': 'Chef de projet',
  'hourly_rate': 50,
  'weekly_hours_worked': 32,
  'contract_hours': 37},
 {'name': 'Paul',
  'job': 'Designer',
  'hourly_rate': 30,
  'weekly_hours_worked': 30,
  'contract_hours': 35}]

In [76]:
import pandas as pd

df = pd.read_csv('/Users/fabgrall/Documents/data_engineer/employes_data_test.csv')

In [77]:
df

,affiliate,name,weekly_hours_worked,contract_hours,hourly_rate,week_salary,monthly_salary,job,highest_salary,mean_salary,lowest_salary
0,TechCorp,Steve,50,37,50,2825.0,11300.0,Chef de projet,11300.0,6975.6,3600.0
1,TechCorp,Bob,45,35,55,2750.0,11000.0,Manager,NaN,NaN,NaN
2,TechCorp,Helen,44,37,50,2375.0,9500.0,Chef de projet,NaN,NaN,NaN
3,TechCorp,Mike,43,40,50,2225.0,8900.0,Chef de projet,NaN,NaN,NaN
4,TechCorp,Bob,48,35,35,1907.5,7630.0,Développeur,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
85,DevInnov,Charlie,41,40,38,1577.0,6308.0,Développeur,NaN,NaN,NaN
86,DevInnov,Grace,37,40,42,1554.0,6216.0,Analyste,NaN,NaN,NaN
87,DevInnov,Lucas,48,40,28,1456.0,5824.0,Testeur,NaN,NaN,NaN
88,DevInnov,Amelia,36,37,38,1368.0,5472.0,Développeur,NaN,NaN,NaN
89,DevInnov,Sophie,43,35,28,1316.0,5264.0,Testeur,NaN,NaN,NaN